server:
  port: 8080

spring:
  application:
    name: lab-mybatis
  datasource:
    url: jdbc:mysql://jenkins.wenpc.com:3306/lab?serverTimezone=GMT%2B8
    username: root
    password: "!QAZ2wsx"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapperLocations: classpath:mapper/*.xml
